### ISSUE TITLE
Text color for buttons do not change the button text color

### ISSUE THREAD

**Issue by hojjatabdollahi** [tarkah/iced-snippets#1]
I'm trying to learn how to create a custom theme in iced using your example. I noticed that there is a field in `button::Appearance` called `text_color`. But since the content of a button is a `Text` widget, the actual text color comes from the `text::StyleSheet` and not `button::StyleSheet`. 

My question is, what is the `text_color` field in `button::Apearance` for? and How can I change the text color of the content of a button based on its type? 

Thank you very much.

**Comment by tarkah** [comment]
The text appearance color is optional, see here:

https://docs.iced.rs/iced/widget/text/struct.Appearance.html

If `None`, it'll inherit from the parent container widget, like button.

**Comment by hojjatabdollahi** [comment]
Thank you. Setting it to `None` works.

**Comment by tarkah** [comment]
Great!
