### ISSUE TITLE
How do we create UI objects outside the inside of the view's rows, etc?

### ISSUE THREAD

**Issue by matteliot** [tarkah/iced-snippets#2]
I see lots of code like:
```
        let inner = container(
            row![container(text("SDfsdf"))]
..more of that here
```
where the row, container, text are made on the fly and without assigning to variables.

But for many reasons, I'd like to do something more like:
```
let x = ..create a container..
let y = ..create something to go inside the container..
x.push(y); //continue adding various things
```

If I do:
`let plainText= text("11SDfsdf");`

I get errors like: 
error[E0284]: type annotations needed for `iced_native::widget::Text<'_, Renderer>`

and including its recommendations on how to fix this don't work and I can't seem to find an answer.

Any ideas? I'm stumped. Thanks

**Comment by matteliot** [comment]
Well- not seconds after posting this, I got it:
        let plainText: iced_native::widget::Text<'_,  crate::widget::Renderer>= text("11SDfsdf");
        let plainText2: iced_native::widget::Text<'_,  crate::widget::Renderer>= text("222");

Thanks for being my rubber duck- please close.

**Comment by tarkah** [comment]
Yeah until you assign the variable into something that ultimately gets returned, the compiler doesn't know how to resolve the generic types.

You shouldn't have to give those hints to the compiler unless the variables are unused (in 99% of cases).
